---
- name: Update Ubuntu 24.04 system
  hosts: all
  become: yes

  tasks:
    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all installed packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
