---
- name: Update and upgrade packages on Ubuntu 24.04, SUSE 15, and RHEL 10
  hosts: ATT_UBUNTU
  become: yes
  tasks:

    - name: Update & upgrade packages on Debian/Ubuntu [ATT_UBUNTU]
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update all packages on RedHat/CentOS/RHEL [INDIA_REDHAT]
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update all packages on SUSE [INDIA_SUSE]
      zypper:
        name: '*'
        state: latest
      when: ansible_os_family == "Suse"

    - name: Gather system facts
      setup:

    - name: Show OS and Kernel version after updates
      debug:
        msg: |
          {{ inventory_hostname }}:
            OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
            Kernel: {{ ansible_kernel }}
